import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { Inter as MyFontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import Script from "next/script";
import { SocketProvider } from "@/app/components/providers/socket-provider";

const fontSans = MyFontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      {/* <html lang="en">
        <body className={inter.className}>{children}</body>
      </html> */}
      <SocketProvider>
        <html lang="en" suppressHydrationWarning>
          <head />
          <body
            className={cn(
              "min-h-screen bg-background font-sans antialiased",
              fontSans.variable
            )}
          >
            {children}
          </body>
        </html>
      </SocketProvider>
    </AuthProvider>
  );
}
